name: Deploy slides

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository with submodules
        uses: actions/checkout@v4
        with:
          submodules: true     # 🔑 fetch the Reveal.js submodule

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: .              # deploy entire repo (talk1/, talk2/, reveal/)

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
