name: Deploy slides
on:
  push: { branches: [ main ] }
  pull_request:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (with submodules)
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Generate index.html (root)
        run: |
          set -euo pipefail
          {
            cat <<'HTML'
<!doctype html><html lang="en"><head><meta charset="utf-8">
<title>My Talks</title>
<style>
  body { font-family: system-ui, sans-serif; max-width: 50rem; margin: 2rem auto; padding: 0 1rem; }
  h1 { margin: 0 0 1rem; }
  ul { list-style: none; padding: 0; }
  li { margin: .4rem 0; }
  a { text-decoration: none; color: #1565c0; font-weight: 500; }
  a:hover { text-decoration: underline; }
</style></head><body><h1>My Talks</h1><ul>
HTML
            # list only first-level dirs that contain index.html
            for d in */ ; do
              [ -f "${d}index.html" ] || continue
              name="${d%/}"
              title=$(grep -m1 -oP '(?i)(?<=<title>).*?(?=</title>)' "${d}index.html" || true)
              [ -n "$title" ] || title="$name"
              printf '<li><a href="%s/">%s</a></li>\n' "$name" "$title"
            done
            echo '</ul></body></html>'
          } > index.html

      - name: Configure Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact (root)
        uses: actions/upload-pages-artifact@v3
        with:
          path: .

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        uses: actions/deploy-pages@v4